### ISSUE TITLE
Add support for UNLISTEN

### ISSUE THREAD

**Issue by patrickmichalina** [porsager/postgres#133] opened 2020-12-20 04:57 UTC
Correct me if I am wrong but there does not appear to be a way to call `unlisten` with this library?

**Comment by joaopaulobdac** [comment] 2021-01-30 20:30
I need a `unlisten` method as well. Did you try using raw sql?
Something like 
```
await sql`UNLISTEN channel`
```
?

**Comment by Minigugus** [comment] 2021-01-30 23:10
> When you call listen, a dedicated connection will automatically be made to ensure that you receive notifications in real time. This connection will be used for any further calls to listen. Listen returns a promise which resolves once the LISTEN query to Postgres completes, or if there is already a listener active.

You're right, there isn't a proper way to unlisten to a channel. Also, since a dedicated connection is used for listening, `await sql`UNLISTEN channel`;` shouldn't work properly (and if even if it works, it won't remove listeners and cause a memory leak).

The only solution for now seems to create a `sql` instance per listen call, then `sql.end()` on specific instances to "unlisten" I guess :neutral_face:

**Comment by porsager** [comment] 2021-02-12 08:50
Wow, can't believe I missed this :P Should definitely be added.

**Comment by stalniy** [comment] 2021-02-24 10:40
@porsager I also need this feature. Looks like feature development is really slow, so I can jump in and do what I care about. So, let's agree on the design and I will send a PR.

My suggestion:

```js
const subscription = await sql.listen('topic', () => {});

subscription.state // { pid: 1, command: 'listen', secret: ... }
await subscription.dispose() // removes callback, in case this is the last callback it calls `unlisten` automatically
```

**Comment by porsager** [comment] 2021-02-24 10:47
@stalniy yeah, I'm unfortunately really low on time, a PR is much welcomed.

You suggestion looks good, but let's call it `unlisten` instead of dispose.

What is the use case for exposing state?

**Comment by stalniy** [comment] 2021-02-24 10:56
The state is currently exposed, I thought it's by design :)

**Comment by porsager** [comment] 2021-03-23 21:14
This is merged and will be included with next beta release

**Closed by porsager** 2021-03-23 21:14 UTC
