### ISSUE TITLE
[Bun] TypeError in Postgres.js when Handling Duplicate Key Error

### ISSUE THREAD

**Issue by rafaelrcamargo** [porsager/postgres#675] opened 2023-09-12 04:41 UTC
# Issue: 
I encountered a TypeError while using Postgres.js when handling a specific database error, which occurs when a duplicate key value violates a unique constraint. This error is disrupting my application's performance and causing server lag, likely due to the error message not being handled correctly.

## Error Details:
```
TypeError: undefined is not an object (evaluating 'query.origin.replace')
  at queryError (/usr/app/node_modules/postgres/src/connection.js:387:34)
  at errored (/usr/app/node_modules/postgres/src/connection.js:381:13)
  at data (/usr/app/node_modules/postgres/src/connection.js:317:8)
  at addChunk (node:stream:1940:42)
  at readableAddChunk (node:stream:1894:58)
  at data (node:net:44:16)
382 |     initial && (queryError(initial, err), initial = null)
383 |   }
384 | 
385 |   function queryError(query, err) {
386 |     query.reject(Object.create(err, {
387 |       stack: { value: err.stack + query.origin.replace(/.*\n/, '\n'), enumerable: options.debug },
```

## Specifics:
- Postgres.js Version: `3.3.5`
- Database Error: ERROR: duplicate key value violates unique constraint "id_pk"

## Expected Behavior:
I expect that when a duplicate key error occurs in the database, it is handled gracefully without causing a TypeError, and it does not impact the server's performance negatively.

> **Additional Information:**
I am using Bun as the application framework. Is there a way to disable or customize the error handling for duplicate key violations to prevent this issue from occurring and causing server lag?

Thank you for your assistance.

**Comment by porsager** [comment] 2023-09-12 07:45
Thanks for the very nice report.

Is the query a tagged query, or are you using `unsafe()`?

**Comment by rafaelrcamargo** [comment] 2023-09-12 18:08
Nope, just a tagged query: ```await sql`INSERT INTO PESSOAS (ID, NOME, APELIDO, NASCIMENTO, STACK) VALUES (${id}, ${nome}, ${apelido}, ${nascimento}, ${stack})`;```

**Comment by rafaelrcamargo** [comment] 2023-09-12 18:20
To give more context this is happening in a really specific scenario, I have 2 API's running behind a NGINX load balancer and this error happens when I repeat the same insert request and the different API's handle the request: 

### Handler:
```ts
const create = async (req: Context<"/pessoas", "json">) => {
  if (!isValid(req.data)) return unprocessableEntity();

  try {
    const { nome, apelido, nascimento, stack } = req.data;
    const id = randomUUID();

    await sql`INSERT INTO PESSOAS (ID, NOME, APELIDO, NASCIMENTO, STACK) VALUES (${id}, ${nome}, ${apelido}, ${nascimento}, ${stack})`;

    return new Response("", {
      headers: { Location: `/pessoas/${id}` },
      status: 201,
    });
  } catch {
    console.log("Created (Catch)");
    return unprocessableEntity();
  } finally {
    console.log("Created (Finally)");
  }
};
```

### Logs:
```
api-1    | Created (Finally)

db-1     | 2023-09-12 18:11:26.645 GMT [2067] ERROR:  duplicate key value violates unique constraint "id_pk"
db-1     | 2023-09-12 18:11:26.645 GMT [2067] DETAIL:  Key (apelido)=(pedroalves) already exists.
db-1     | 2023-09-12 18:11:26.645 GMT [2067] STATEMENT:  INSERT INTO PESSOAS (ID, NOME, APELIDO, NASCIMENTO, STACK) VALUES ($1, $2, $3, $4, $5)
api-2    | Created (Catch)
api-2    | Created (Finally)

db-1     | 2023-09-12 18:11:28.921 GMT [2067] ERROR:  duplicate key value violates unique constraint "id_pk"
db-1     | 2023-09-12 18:11:28.921 GMT [2067] DETAIL:  Key (apelido)=(pedroalves) already exists.
db-1     | 2023-09-12 18:11:28.921 GMT [2067] STATEMENT:  INSERT INTO PESSOAS (ID, NOME, APELIDO, NASCIMENTO, STACK) VALUES ($1, $2, $3, $4, $5)
api-2    | Created (Catch)
api-2    | Created (Finally)

db-1     | 2023-09-12 18:11:30.969 GMT [2069] ERROR:  duplicate key value violates unique constraint "id_pk"
db-1     | 2023-09-12 18:11:30.969 GMT [2069] DETAIL:  Key (apelido)=(pedroalves) already exists.
db-1     | 2023-09-12 18:11:30.969 GMT [2069] STATEMENT:  INSERT INTO PESSOAS (ID, NOME, APELIDO, NASCIMENTO, STACK) VALUES ($1, $2, $3, $4, $5)
api-1    | 382 |     initial && (queryError(initial, err), initial = null)
api-1    | 383 |   }
api-1    | 384 | 
api-1    | 385 |   function queryError(query, err) {
api-1    | 386 |     query.reject(Object.create(err, {
api-1    | 387 |       stack: { value: err.stack + query.origin.replace(/.*\n/, '\n'), enumerable: options.debug },
api-1    |                                       ^
api-1    | TypeError: undefined is not an object (evaluating 'query.origin.replace')
api-1    |       at queryError (/usr/app/node_modules/postgres/src/connection.js:387:34)
api-1    |       at errored (/usr/app/node_modules/postgres/src/connection.js:381:13)
api-1    |       at data (/usr/app/node_modules/postgres/src/connection.js:317:8)
api-1    |       at addChunk (node:stream:1940:42)
api-1    |       at readableAddChunk (node:stream:1894:58)
api-1    |       at data (node:net:44:16)
api-1    | 382 |     initial && (queryError(initial, err), initial = null)
api-1    | 383 |   }
api-1    | 384 | 
api-1    | 385 |   function queryError(query, err) {
api-1    | 386 |     query.reject(Object.create(err, {
api-1    | 387 |       stack: { value: err.stack + query.origin.replace(/.*\n/, '\n'), enumerable: options.debug },
api-1    |                                       ^
api-1    | TypeError: undefined is not an object (evaluating 'query.origin.replace')
api-1    |       at queryError (/usr/app/node_modules/postgres/src/connection.js:387:34)
api-1    |       at errored (/usr/app/node_modules/postgres/src/connection.js:381:13)
api-1    |       at data (/usr/app/node_modules/postgres/src/connection.js:317:8)
api-1    |       at addChunk (node:stream:1940:42)
api-1    |       at readableAddChunk (node:stream:1894:58)
api-1    |       at data (node:net:44:16)
```

**Comment by sprightlydev** [comment] 2023-09-16 15:37
@rafaelrcamargo I think you'll want to handle the error at the call to `sql()`, and can chain it right to the end of the template literal like [this](https://github.com/porsager/postgres/blob/master/tests/index.js#L338). [There are several variations of this in the tests, if you want more examples.]

Btw you could probably let Postgres generate those UUID's for you, and grab the result with [`returning`](https://github.com/porsager/postgres#await-sql---result).

**Comment by rafaelrcamargo** [comment] 2023-09-16 17:48
Hey @sprightlydev, thanks for the tips, just to disclose somethings, this is not a production app, so I'm simplifying somethings, like the UUID, but I had thought about it also.

As for the `.catch` I've tried it, but this error is not returned, is thrown from a `queryError` function witch does not handle this error, maybe `Bun` returns or uses some different data structures witch creates this unexpected behavior.

**Comment by dmythro** [comment] 2023-10-04 10:35
Yeah, just noticed I can't query anything with `Bun` as well (v1.0.4) with the same error.
Example:

```ts
const itemCount = await sql`SELECT COUNT(*) as count FROM "${customerKey}"."items"`
```

**Comment by porsager** [comment] 2023-10-04 10:45
@dmythro that's not a valid query, so I don't think it's related. You need to remove the quotes around customerKey and wrap the variable in `sql()` - check the docs.

**Comment by notramo** [comment] 2023-10-06 18:57
The Bun runtime is awesome, however it still has a lot of room for improvement. Node compatibility is not 100% yet, and many popular NPM package don't work out of the box in Bun.
So, in order to find out if it's a Bun issue or an actual bug in the `postgres` package, I recommend reproducing it in Node.

**Comment by rafaelrcamargo** [comment] 2023-10-25 14:39
> The Bun runtime is awesome, however it still has a lot of room for improvement. Node compatibility is not 100% yet, and many popular NPM packages don't work out of the box in Bun.

For sure, this seems like the object on the error handling is in a different shape than the expected, probably something that differs from one runtime to another.

For now I will keep this open, but will mark it as  a [Bun] related problem, and let it up to the contributors to choose whether this is a priority or not.

*Just for curiosity sake I fixed it for my project, but in `bun` I'm also not really sure how this will behave in `node` then.*

And thanks for the time y'all! 😄

**Comment by porsager** [comment] 2023-10-26 21:21
I think I'll close this out, since bun is moving fast ;) reopen if it's still an issue

**Closed by porsager** 2023-10-26 21:21 UTC
