### ISSUE TITLE
Implement COPY table TO/FROM STDOUT/STDIN

### ISSUE THREAD

**Issue by uasan** [porsager/postgres#170] opened 2021-03-31 22:29 UTC
Hello.
We using `node-pg-copy-streams`
https://github.com/brianc/node-pg-copy-streams

`COPY table FROM STDIN` - for import large csv file to table.
`COPY table TO STDOUT` - for export from large table to csv file.

We, and I think many, cannot use `COPY table FROM/TO '/local/file.csv'` the option for the Postgres server to read the file from the local file system, because the web server (which upload or download) does not have the permissions to read and write to the file on the server database.

This is the only reason why we cannot use your library on our project.
Do you think the implementation of this functionality is possible in the foreseeable future?
Thanks.

**Comment by porsager** [comment] 2021-04-06 08:31
Hi @uasan .

That's a great idea! 

I actually have a use case for this myself currently, so let's see if we can get that added.

What do you think about the following API ?

```js
const readableStream = sql`copy table_name to stdout`.readable()

const writableStream = sql`copy table_name from stdin`.writable()
```

**Comment by uasan** [comment] 2021-04-06 08:42
> What do you think about the following API ?

If methods `readable ` and `writable`, return native JS streams, then this interface suits us perfectly.

**Comment by porsager** [comment] 2021-04-06 08:43
That was the idea 👍

**Comment by uasan** [comment] 2021-06-05 14:01
I would like to somehow help speed up the implementation of export import streaming.
Can you tell me in which internal API should be used, I would try to implement the PR, is this an option?

**Comment by porsager** [comment] 2021-06-25 10:48
Would you mind giving the copy branch a test? 

I've just used it on some of my own systems with success (copy the maxmind geolite ip dataset).

**Comment by uasan** [comment] 2021-06-25 11:08
I will definitely check, thanks!

**Comment by uasan** [comment] 2021-06-25 16:11
A very quick test, then I will do a more detailed one.
If execute query
```JS
const sql = postgres(...);
const writable = sql`COPY table FROM STDIN WITH(FORMAT csv, HEADER true, DELIMITER ',')`.writable();
writable.write(....'\n');
```
Error:
```
Cannot set property 'blocked' of undefined
```

**Comment by porsager** [comment] 2021-06-25 16:53
Ah, got it. I'm working on an improvement on query queueing for this, but I've pushed a commit that fixes this issue for now. Let me know how it works now ;)

**Comment by uasan** [comment] 2021-06-25 20:31
Everything works fine now! 
There is an interesting feature, on the same file and table, the [pg-copy-streams](https://github.com/brianc/node-pg-copy-streams) module raises many `drain` events and we wait for the backpressure to complete, your module does not raise more than one `drain` event and everything completes successfully, I wonder why this is?

**Comment by porsager** [comment] 2021-06-25 21:20
Right, the exposed stream is not tied to the actual (tcp/socket) connection (yet), so if you check memory, there is probably more buildup than with `pg-copy-streams`.

**Comment by uasan** [comment] 2021-06-25 21:45
I understand, but it will be a problem if the file size exceeds the amount of available memory, what are your plans for the final implementation?

**Comment by porsager** [comment] 2021-06-25 21:49
To hook it up to the (tcp/socket) stream (hence the `(yet)` above.)

**Comment by porsager** [comment] 2021-06-25 21:52
I'm currently toying around with getting realtime changes through the replication stream, which also uses the `Copy` parts of the protocol, so the internal design is still a moving target to make sure I end up with a good final design.

**Comment by porsager** [comment] 2021-06-27 08:57
Ok, backpressure is now handled for both readable and writable. Mind trying to see how it works for you now?

**Comment by uasan** [comment] 2021-06-27 13:30
Yes, I try new version...

**Comment by uasan** [comment] 2021-06-27 13:56
Not emit event `drain`:
```JS
  const writable = sql`COPY table FROM STDIN `.writable();
  writable.on('drain', console.log);
```
But call function callback:
```JS
await { then(resolve) { writable.write(chank, 'utf8', resolve) } }
```
It will be great if streams are always promises, please use Streams Promises API
https://nodejs.org/api/stream.html#stream_streams_promises_api

**Comment by uasan** [comment] 2021-06-27 19:14
Made a promisify stream, very simple and cost-effective for the garbage collector

```JS
  const promisify = stream => {
    let resolve;
    let reject;

    const callback = error => {
      if (error) reject(error);
      else resolve();
    }

    const promise = {
      then(resolveNative, rejectNative) {
        resolve = resolveNative;
        reject = rejectNative;
      }
    };

    stream.writeAsync = (chunk, encoding) => {
      stream.write(chunk, encoding, callback);
      return promise;
    }
  }
```
Usage:
```JS
const stream = sql`COPY table FROM STDIN`.writable();
promisify(stream);

while(chunk = getNextChunk()) {
 await stream.writeAsync(chunk);
}

```

**Comment by porsager** [comment] 2021-06-28 07:58
Ah, yeah that seems way more convenient, but unless it can work seamlessly with regular streams, I don't want to require node 15 for that functionality yet.

Just to be sure, it works as intended with the latest commit right?

**Comment by uasan** [comment] 2021-06-28 09:29
> Just to be sure, it works as intended with the latest commit right?

Yes, thanks for the job.

**Comment by uasan** [comment] 2021-07-18 14:10
Connection hangs, after abort a stream, because of this, the Node.js process in eternal anticipation.

Node.js v16.5
```JS
import postgres from 'postgres';
import { createReadStream } from 'fs';
import { addAbortSignal } from 'stream';

const sql = postgres();

const testCopy = async () => {
  const controller = new AbortController();
  const readable = createReadStream(pathFileCSV);

  const writable = sql`COPY table FROM STDIN WITH(FORMAT csv, HEADER true, DELIMITER ',')`.writable();

  readable
    .pipe(addAbortSignal(controller.signal, writable))
    .on('error', () => {
      console.log('ABORTED-STREAM');
    });

  setTimeout(async () => {
    controller.abort();
    await sql.end();
    console.log('DB END'); // this never executed
  }, 32)
}

testCopy();
```

**Comment by porsager** [comment] 2021-08-13 06:53
Hi @uasan ..

Could you maybe create a full test showing this issue? I've just tried your pasted example above, and it seems to work for me.

**Comment by porsager** [comment] 2021-08-13 07:30
Should be fixed with 4356ae9

**Comment by uasan** [comment] 2021-08-13 13:00
Ok, when are you planning to merge it into the master?

**Comment by porsager** [comment] 2021-08-13 13:01
Now 🙂 Then I'll make a new beta release with it.

**Closed** 2021-08-13 13:02 UTC
Labels: enhancement
