### ISSUE TITLE
Speed up running many statements with sql.unsafe

### ISSUE THREAD

**Issue by bfelbo** [porsager/postgres#47] opened 2020-03-12 18:40 UTC
Hello, this library is really promising and it's amazing to see how much it's improving every month!

As part of our testing, we send multiple statements at a time using `sql.unsafe()`. This is needed both for resetting parts of the DB (i.e. delete all rows in a few tables and insert them from SQL files) and for testing logic inside a transaction (i.e. modify the DB state with a few statements, then run some functions and finally rollback). However, it seems that sending multiple statements is as slow as sending them individually. Is each statement sent over the network individually? If so, would it be possible to them all in a single network request?

That would speed up our testing substantially. Similarly, I can easily imagine other development/testing use cases, where this library would then be much faster.

**Comment by bfelbo** [comment] 2020-03-12 18:49
I did some informal testing with `resetPostgresDevData` involving hundreds of statements (mainly deletes and inserts) using `sql.unsafe()` vs. node-pg's `pool.query()`. This was after warming the DB and repeated twice in different order to ensure that didn't impact results.

node-pg seems to be approx. 15% faster. It would be awesome if Postgres.js could also be the fastest library for this use case :)

```
const resetTables = async function() {
  // Time difference
  const start = new Date()
  for (let i=0; i<1000; i++) {
    await resetPostgresDevData()
  }
  // @ts-ignore
  console.log(new Date() - start)
  process.exit(0)
}
resetTables()
```

**Comment by porsager** [comment] 2020-03-12 19:33
Hi @bfelbo .. Thanks a lot! I'm glad it seems so, cause I actually haven't had the time available that I hoped to move on things, but hopefully the next couple of weeks looks better.

So there are several things that come into play. For one, `sql.unsafe` is not optimized the same way as ``` sql`` ``` is, but I do have plans to add opt-in options to get almost the same speed with `sql.unsafe`. I'll let you know here when it's on master ;) Also when you use unsafe it infers if it should send a simple query or not depending on if you supply any arguments.

I promise you, queuing, network transfer is as optimized as I think is currently possible, but again, it depends on your query so if you could post that too, it'd be easer to tell what's going on.

Also currently the default pool size is `os.cpus().length`, but I think I'll change that to `10` as that seems like a better production default. If you could try set `{ max: 10 }` in options too that would be interesting.

About your code sample, you are opting out of any kind of concurrency with the for loop, so it will be slow since you're not piping requests as fast as you could, and you're not using the connection pool.

Try to do this instead:
```
const start = new Date()
Promise.all([...Array(1000)].map(() => runManyStatements())
console.log(new Date() - start)
```

I'd love to see a test case for the `pg` comparisson. You can see the benchmarks I've done here: https://github.com/porsager/postgres-benchmarks

**Comment by bfelbo** [comment] 2020-03-13 22:43
Thanks a lot for the detailed answer. It sounds great that you're working on optimizations for `sql.unsafe`!

> Also currently the default pool size is `os.cpus().length`, but I think I'll change that to `10` as that seems like a better production default. If you could try set `{ max: 10 }` in options too that would be interesting.

I didn't fully write out the code for the test I did above, but I actually set `{ max: 10 }` for both libraries to make it fair. However, I don't think this'll matter much (see my next comment).
 
> About your code sample, you are opting out of any kind of concurrency with the for loop, so it will be slow since you're not piping requests as fast as you could, and you're not using the connection pool.

Yes, this is intentional. The for loop is only to get more reliable results. I'm asking if Postgres.js could speed up running a large number of statements sent as a single query (non-concurrency). For instance:
```
UPDATE device SET active = FALSE WHERE user_id = 1;
INSERT INTO device (user_id, device_id, active) VALUES (1, 100, TRUE);
SELECT * FROM active_devices_by_user(1);
```
We have many such tests. It seems currently that Postgres.js sends each statement separately despite all the statements being in the same transaction and just being sent as a string using `sql.unsafe`. It would be great if the statements could be sent together to avoid network roundtrips and thereby make it faster.

I looked into https://github.com/porsager/postgres-benchmarks. It seems that these benchmarks are focused on testing performance using concurrency against a local Postgres DB. We would probably have to modify the setup a bit to make it a good benchmarking setup for measuring this.

Does this make sense? :)

**Comment by porsager** [comment] 2020-03-15 19:52
> Yes, this is intentional. The for loop is only to get more reliable results. I'm asking if Postgres.js could speed up running a large number of statements sent as a single query (non-concurrency). 

You are preventing the library from doing exactly what you're asking because of that for loop. Postgres.js cannot know about the next query before it has received a response for the first query. It's impossible due to how Javascript works. As said earlier, Postgres.js is already optimized as much as possible, but you have to use it right to benefit from it. 

Maybe you could put a full reproducible sample somewhere. That would make it easier to tell what's going on.

> It seems currently that Postgres.js sends each statement separately despite all the statements being in the same transaction.

As you might have noticed you cannot send multiple statements using ``` sql`` ```. Is that why you are using `sql.unsafe`? 

The PostgreSQL protocol is built up such that you have `simple` and `extended` queries. Simple queries cannot have parameters, but can contain multiple statements. Extended can only contain a single statement, but can have parameters.

If you have eg.
```js
sql.unsafe(`
  UPDATE device SET active = FALSE WHERE user_id = 1;
  INSERT INTO device (user_id, device_id, active) VALUES (1, 100, TRUE);
  SELECT * FROM active_devices_by_user(1);
`)
```
Postgres.js will use a simple query. If you tried adding parameters (2nd argument) to that query you would get an error because Postgres.js would try to make an extended query, and hence the database would throw an error because that extended query contains multiple statements.

So. If you can make a query like the above and it works, Postgres.js does send those 3 statements together as a simple query. That doesn't mean it's the fastest. It could very well be faster to do a transaction like below, but it would need to be tested:
```js
sql.begin(sql => [
  sql`UPDATE device SET active = FALSE WHERE user_id = 1;`,
  sql`INSERT INTO device (user_id, device_id, active) VALUES (1, 100, TRUE);`,
  sql`SELECT * FROM active_devices_by_user(1);`
])
```

With regards to the benchmarks they use a pool size of 4 to give the optimum scenario for all libraries on my machine where I have 4 cores available. It doesn't change much if I run on a single connection, Postgres.js is still magnitudes faster. (numbers below)

client     |         select |     select_arg |    select_args |   select_where
:--------- | -------------: | -------------: | -------------: | -------------:
postgres   |  0.230s (4.2x) |  0.253s (5.8x) |  0.618s (3.8x) |  0.739s (5.0x)
pg         |  0.963s (1.0x) |  1.465s (1.0x) |  2.373s (1.0x) |  3.685s (1.0x)

It would be really great if you could provide a reproducible test setup where you are seeing slower performance than expected, so that I can look closer at it :)

**Comment by porsager** [comment] 2020-04-06 14:15
I'll just close this out for now 😉 Feel free to reopen if you get som more info.

**Closed** 2020-04-06 14:15 UTC
Labels: enhancement, question
